In [2]:
import torch 
import numpy as np

In [3]:
print(torch.ones(5))
a=np.linalg.inv([[1,1],[0,1]])
print(a)

tensor([1., 1., 1., 1., 1.])
[[ 1. -1.]
 [ 0.  1.]]


In [4]:
import time
a=time.time()
print(type(a))

<class 'float'>


In [5]:

scale=3
para_num=5
a=2*scale*torch.rand(para_num)-scale
print(a)
print(a[0:2])

tensor([ 1.5965,  1.8596, -2.3153, -2.0749, -1.5420])
tensor([1.5965, 1.8596])


In [12]:
a=torch.randint(0,100,(3,4))
b=torch.randint(0,100,(3,4))
c=torch.randint(0,100,(3,4))
e=torch.concatenate((a,b,c),dim=0)
f=torch.stack((a,b,c),dim=0)
g=torch.concatenate((f,f),dim=0)
print(a)
print(b)
print(c)
print(e)
list=[a,b,c]
k=torch.cat(list,dim=0)
print(k)
print(f)


tensor([[51, 58, 89, 23],
        [93, 71, 11, 47],
        [23, 59, 23, 36]])
tensor([[11, 96,  2, 58],
        [70, 93, 30, 31],
        [40, 59, 12, 27]])
tensor([[91, 25, 29, 15],
        [88, 90, 63,  1],
        [41, 50, 34, 73]])
tensor([[51, 58, 89, 23],
        [93, 71, 11, 47],
        [23, 59, 23, 36],
        [11, 96,  2, 58],
        [70, 93, 30, 31],
        [40, 59, 12, 27],
        [91, 25, 29, 15],
        [88, 90, 63,  1],
        [41, 50, 34, 73]])
tensor([[51, 58, 89, 23],
        [93, 71, 11, 47],
        [23, 59, 23, 36],
        [11, 96,  2, 58],
        [70, 93, 30, 31],
        [40, 59, 12, 27],
        [91, 25, 29, 15],
        [88, 90, 63,  1],
        [41, 50, 34, 73]])
tensor([[[51, 58, 89, 23],
         [93, 71, 11, 47],
         [23, 59, 23, 36]],

        [[11, 96,  2, 58],
         [70, 93, 30, 31],
         [40, 59, 12, 27]],

        [[91, 25, 29, 15],
         [88, 90, 63,  1],
         [41, 50, 34, 73]]])


In [7]:
a=torch.randint(0,100,(3,4))
b=torch.randint(0,100,(3,2))
c=torch.concatenate((a,b),dim=-1)
print(a)
print(b)
print(c)
print(a[0:2].view(-1))   

tensor([[79, 46, 65, 58],
        [64,  6, 46, 44],
        [ 6, 79,  1, 48]])
tensor([[20, 54],
        [33, 56],
        [49, 25]])
tensor([[79, 46, 65, 58, 20, 54],
        [64,  6, 46, 44, 33, 56],
        [ 6, 79,  1, 48, 49, 25]])
tensor([79, 46, 65, 58, 64,  6, 46, 44])


In [8]:
import torch

# 创建一个形状为 (3, 4) 的张量
tensor = torch.tensor([[10, 20, 30, 40],
                       [5, 1, 25, 35],
                       [1.5, 2, 3, 4]], dtype=torch.float32)

# 选取最小的 2 个元素
values, indices = torch.topk(tensor.view(-1), k=2, largest=False)

print("最小的 2 个元素:", values)
print("对应的索引:", indices)

最小的 2 个元素: tensor([1.0000, 1.5000])
对应的索引: tensor([5, 8])


In [9]:
width=torch.tensor([4,0.01,0.01])
alpha_list=2*width*torch.rand(3)-width
print(alpha_list)

tensor([ 1.9514, -0.0060,  0.0041])


In [10]:
# torch.save(target_alpha,f'./target_alpha/alpha_{epoch}_{batch}_{count}.pt')
# torch.save(data_eig,f'./data_eigenvalue/eigenvalues_{epoch}_{batch}_{count}.pt')
epoch=2
batch=16
count=1
a=torch.load(f'./target_alpha/alpha_{epoch}_{batch}_{count}.pt')
b=torch.load(f'./data_eigenvalue/eigenvalues_{epoch}_{batch}_{count}.pt')
print(a)
print(b)

/tmp/ipykernel_3091835/512266182.py:6: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  a=torch.load(f'./target_alpha/alpha_{epoch}_{batch}_{count}.pt')


tensor([[[ 2.9542e-01, -1.0932e-02,  7.4956e-03, -9.4731e-04,  8.9720e-03],
         [ 1.6053e-01,  7.6751e-02,  9.4413e-03,  7.1351e-03,  1.7106e-03],
         [ 7.6759e-02, -1.4104e-02, -8.7482e-03, -5.2837e-03,  5.4952e-05],
         [ 1.0731e-01,  2.5833e-02, -1.8295e-04, -2.8747e-03,  6.3025e-03],
         [ 1.8183e-01,  9.4636e-02,  6.8653e-03, -4.0535e-03,  3.8740e-03],
         [ 1.0170e+00,  8.0649e-02,  5.4375e-03, -6.8647e-03,  6.6465e-03],
         [ 1.2206e+00, -3.5588e-02,  2.8816e-03,  1.1705e-03,  9.1798e-03],
         [ 1.6783e+00, -7.4236e-02, -7.8886e-03,  8.3530e-03,  9.7827e-03],
         [ 1.3856e+00,  6.0639e-02,  8.5798e-03, -7.3877e-03,  8.1025e-03],
         [ 1.1044e+00, -7.3485e-02, -2.7196e-03,  1.0904e-03, -9.3546e-03],
         [ 7.2959e-01,  4.4877e-02,  3.1615e-04,  8.6137e-03,  2.6459e-03],
         [ 1.6527e-01, -8.4722e-02,  6.4335e-03, -7.5076e-03, -6.2747e-03],
         [ 8.4470e-01, -8.1355e-02, -4.1135e-03,  6.0192e-03,  4.4913e-03],
         [ 2

/tmp/ipykernel_3091835/512266182.py:7: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  b=torch.load(f'./data_eigenvalue/eigenvalues_{epoch}_{batch}_{count}.pt')


In [ ]:
import torch
x=torch.tensor([1,2,3,4,5])-3
mask1=(x>0).float()
mask2=(x<0).float()
print(mask1)
print(mask2)

tensor([0., 0., 0., 1., 1.])
tensor([1., 1., 0., 0., 0.])


In [11]:
import torch

# 定义一个示例函数
x = torch.tensor([1.0 , 2.0], requires_grad=True)  # 确保启用梯度计算
y = x**3  # 示例函数 y = x^3

# 计算一阶导数
grad_1 = torch.autograd.grad(y, x ,grad_outputs=torch.ones_like(y), create_graph=True)[0]

print(grad_1)  # 输出 12.0
# 计算二阶导数
grad_2 = torch.autograd.grad(grad_1, x,grad_outputs=torch.ones_like(x))[0]

print( grad_2)  

tensor([ 3., 12.], grad_fn=<MulBackward0>)
tensor([ 6., 12.])
