In [134]:
import torch
import torch.nn as nn
class Mynetwork(nn.Module):
    def __init__(self,input_num=1 , out_num=1,hidden_num=16):
        super().__init__()
        self.MLP=nn.Sequential(
            nn.Linear(input_num, hidden_num),
            nn.ELU(),
            nn.Linear(hidden_num,hidden_num),
            nn.ELU(),
            nn.Linear(hidden_num,out_num),
        )
        pass
    def forward(self,x):
        return self.MLP(x)

In [135]:
prime=torch.tensor([[2,3,5,7],[11,13,17,19],[23,29,31,37],[41,43,47,53]],dtype=torch.float32)/5
print(prime.det())

rank=1000
use=6
dtype=torch.float32
device='cuda' if torch.cuda.is_available() else 'cpu'
print('device:',device)
k=torch.tensor([i for i in range(1,rank+1)],dtype=dtype,device=device)
print('eigvalues:'  ,k)

A=torch.diag(k)
rand=torch.randn(rank,rank,dtype=dtype,device=device)
while torch.abs(rand.det())<0.1:
    rand=torch.randn(rank,rank,dtype=dtype,device=device)
rand_inv=torch.inverse(rand)

A=rand_inv@A@rand
print(A)

eigenvalues= torch.linalg.eigvals(A).real
eigenvalues , _= torch.sort(eigenvalues)
print(eigenvalues)

tensor(1.4080)
device: cuda
eigvalues: tensor([   1.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,    9.,   10.,
          11.,   12.,   13.,   14.,   15.,   16.,   17.,   18.,   19.,   20.,
          21.,   22.,   23.,   24.,   25.,   26.,   27.,   28.,   29.,   30.,
          31.,   32.,   33.,   34.,   35.,   36.,   37.,   38.,   39.,   40.,
          41.,   42.,   43.,   44.,   45.,   46.,   47.,   48.,   49.,   50.,
          51.,   52.,   53.,   54.,   55.,   56.,   57.,   58.,   59.,   60.,
          61.,   62.,   63.,   64.,   65.,   66.,   67.,   68.,   69.,   70.,
          71.,   72.,   73.,   74.,   75.,   76.,   77.,   78.,   79.,   80.,
          81.,   82.,   83.,   84.,   85.,   86.,   87.,   88.,   89.,   90.,
          91.,   92.,   93.,   94.,   95.,   96.,   97.,   98.,   99.,  100.,
         101.,  102.,  103.,  104.,  105.,  106.,  107.,  108.,  109.,  110.,
         111.,  112.,  113.,  114.,  115.,  116.,  117.,  118.,  119.,  120.,
         121.,  122.,  12

In [136]:
NN=Mynetwork(1,1).to(dtype=dtype,device=device)
input=torch.tensor([i for i in range(rank)],dtype=dtype,device=device).unsqueeze(-1)
print(NN(input))

tensor([[-3.0992e-01],
        [ 4.8109e-02],
        [ 3.3442e-01],
        [ 5.4022e-01],
        [ 7.0018e-01],
        [ 8.3119e-01],
        [ 9.4235e-01],
        [ 1.0424e+00],
        [ 1.1357e+00],
        [ 1.2249e+00],
        [ 1.3114e+00],
        [ 1.3963e+00],
        [ 1.4804e+00],
        [ 1.5643e+00],
        [ 1.6478e+00],
        [ 1.7310e+00],
        [ 1.8138e+00],
        [ 1.8962e+00],
        [ 1.9783e+00],
        [ 2.0603e+00],
        [ 2.1420e+00],
        [ 2.2237e+00],
        [ 2.3052e+00],
        [ 2.3865e+00],
        [ 2.4679e+00],
        [ 2.5491e+00],
        [ 2.6302e+00],
        [ 2.7114e+00],
        [ 2.7924e+00],
        [ 2.8734e+00],
        [ 2.9544e+00],
        [ 3.0354e+00],
        [ 3.1163e+00],
        [ 3.1972e+00],
        [ 3.2781e+00],
        [ 3.3589e+00],
        [ 3.4398e+00],
        [ 3.5206e+00],
        [ 3.6014e+00],
        [ 3.6822e+00],
        [ 3.7629e+00],
        [ 3.8437e+00],
        [ 3.9244e+00],
        [ 4

In [137]:
output=NN(input)
diag=torch.diag(output.flatten())

up_diag=torch.ones(rank - 1,dtype=dtype,device=device) *10

B=diag+torch.diag(up_diag,1)+torch.diag(up_diag,-1)
print(B)

tensor([[-3.0992e-01,  1.0000e+01,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 1.0000e+01,  4.8109e-02,  1.0000e+01,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  1.0000e+01,  3.3442e-01,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  8.1280e+01,
          1.0000e+01,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  1.0000e+01,
          8.1361e+01,  1.0000e+01],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          1.0000e+01,  8.1442e+01]], device='cuda:0', grad_fn=<AddBackward0>)


In [138]:
pre_eig=torch.linalg.eigvalsh(B)
print(pre_eig)

tensor([-1.8741e+01, -1.7985e+01, -1.7392e+01, -1.6876e+01, -1.6408e+01,
        -1.5974e+01, -1.5567e+01, -1.5180e+01, -1.4811e+01, -1.4456e+01,
        -1.4113e+01, -1.3782e+01, -1.3461e+01, -1.3148e+01, -1.2843e+01,
        -1.2546e+01, -1.2255e+01, -1.1970e+01, -1.1691e+01, -1.1417e+01,
        -1.1148e+01, -1.0884e+01, -1.0624e+01, -1.0368e+01, -1.0115e+01,
        -9.8668e+00, -9.6217e+00, -9.3799e+00, -9.1413e+00, -8.9056e+00,
        -8.6728e+00, -8.4428e+00, -8.2154e+00, -7.9905e+00, -7.7680e+00,
        -7.5479e+00, -7.3301e+00, -7.1144e+00, -6.9008e+00, -6.6893e+00,
        -6.4797e+00, -6.2720e+00, -6.0662e+00, -5.8621e+00, -5.6598e+00,
        -5.4592e+00, -5.2602e+00, -5.0629e+00, -4.8671e+00, -4.6727e+00,
        -4.4799e+00, -4.2885e+00, -4.0985e+00, -3.9099e+00, -3.7226e+00,
        -3.5367e+00, -3.3520e+00, -3.1685e+00, -2.9863e+00, -2.8053e+00,
        -2.6254e+00, -2.4467e+00, -2.2691e+00, -2.0926e+00, -1.9172e+00,
        -1.7429e+00, -1.5696e+00, -1.3973e+00, -1.2

In [139]:
optimizer=torch.optim.Adam(NN.parameters(),lr=0.01)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer,patience=20,threshold=1e-4)
loss_fn=nn.L1Loss()
for i in range(1000):
    optimizer.zero_grad()
    
    output=NN(input)
    diag=torch.diag(output.flatten())
    B=diag+torch.diag(up_diag,1)+torch.diag(up_diag,-1)
    pre_eig=torch.linalg.eigvalsh(B)
    
    loss=loss_fn(k[:use],pre_eig[:use])
    loss.backward()
    # print(NN.MLP[0].weight.grad)
    optimizer.step()
    scheduler.step(loss)
    if i %10==0:
        print(pre_eig[:use])
        print(loss.item())

tensor([-18.7406, -17.9846, -17.3915, -16.8755, -16.4077, -15.9741],
       device='cuda:0', grad_fn=<SliceBackward0>)
20.72903060913086
tensor([-14.4428,  -9.9381,  -6.5551,  -3.6839,  -1.1289,   1.2023],
       device='cuda:0', grad_fn=<SliceBackward0>)
9.257728576660156
tensor([-10.4882,  -2.6571,   3.0618,   7.8182,  11.9714,  15.6893],
       device='cuda:0', grad_fn=<SliceBackward0>)
6.114349365234375
tensor([-10.5953,  -4.0550,   0.8136,   4.9190,   8.5442,  11.8209],
       device='cuda:0', grad_fn=<SliceBackward0>)
5.020129203796387
tensor([-10.8731,  -5.5974,  -1.5940,   1.8216,   4.8659,   7.6415],
       device='cuda:0', grad_fn=<SliceBackward0>)
4.669737339019775
tensor([-9.1170, -3.4921,  0.7437,  4.3474,  7.5527, 10.4697], device='cuda:0',
       grad_fn=<SliceBackward0>)
4.205853462219238
tensor([-8.6242, -3.6829,  0.0602,  3.2603,  6.1188,  8.7308], device='cuda:0',
       grad_fn=<SliceBackward0>)
3.806029796600342
tensor([-7.3444, -2.6632,  0.8659,  3.8836,  6.5818, 